spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/comeet
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
logging:
  level:
    org.hibernate.SQL: debug #하이버네이트가 생성하는 쿼리문을 다 볼 수 있다.
    org.hibernate.type: trace # 쿼리 파라미터를 ?가 아닌 실제 값으로 볼 수 있게 해준다. 단, p6spy를 추천한다.
server:
  error:
    include-message: always
    include-binding-errors: always